apiVersion: apps/v1
kind: Deployment
metadata:
  name: movierecommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: movie-app
        image: us-central1-docker.pkg.dev/movie-recommender-engine/movie-repo/movie-app:v1
        ports:
        - containerPort: 8501